server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: 106.14.35.196:2081,106.14.35.196:2082,106.14.35.196:2083



